apiVersion: v1
kind: Service
metadata:
  name: pma-service
  namespace: wordpress
spec:
  type: NodePort
  selector:
    app: phpmyadmin
  ports:
    - port: 8001
      targetPort: 80
      nodePort: 30003
